name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > deploy_key.pem
        chmod 600 deploy_key.pem

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        key_path: deploy_key.pem
        port: 22
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo chown -R apache:apache /var/www/html
